# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: travelstory-deployment
#   namespace: "2401149"
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: travelstory
#   template:
#     metadata:
#       labels:
#         app: travelstory
#     spec:
#       containers:
#         - name: travelstory-frontend
#           image: 127.0.0.1:30085/2401149/travelstory-frontend:v1
#           ports:
#             - containerPort: 8080
#           readinessProbe:
#             httpGet:
#               path: /health
#               port: 8080
#             initialDelaySeconds: 5
#             periodSeconds: 10
#           livenessProbe:
#             httpGet:
#               path: /health
#               port: 8080
#             initialDelaySeconds: 10
#             periodSeconds: 20

#         - name: travelstory-backend
#           image: 127.0.0.1:30085/2401149/travelstory-backend:v1
#           ports:
#             - containerPort: 8081
#           readinessProbe:
#             httpGet:
#               path: /health
#               port: 8081
#             initialDelaySeconds: 5
#             periodSeconds: 10
#           livenessProbe:
#             httpGet:
#               path: /health
#               port: 8081
#             initialDelaySeconds: 10
#             periodSeconds: 20
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelstory-deployment
  namespace: "2401149"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelstory
  template:
    metadata:
      labels:
        app: travelstory
    spec:
      imagePullSecrets:
        - name: nexus-credentials

      containers:
        - name: travelstory-frontend
          image: 127.0.0.1:8083/2401149/travelstory-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
