---
apiVersion: v1
kind: Service
metadata:
  name: travelstory-service
  namespace: "2401149"
spec:
  selector:
    app: travelstory
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80

    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travelstory-ingress
  namespace: "2401149"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: travel.imcc.com
      http:
        paths:
          # Frontend (Vite build output)
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: travelstory-service
                port:
                  number: 80

          # Backend API
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: travelstory-service
                port:
                  number: 5000
